apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runner.serviceAccount }}
  namespace: {{ .Values.runner.namespace }}
  labels:
    app.kubernetes.io/part-of: glimmung-runner
    azure.workload.identity/use: "true"
  {{- if .Values.runner.serviceAccountClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.runner.serviceAccountClientId | quote }}
  {{- end }}
